### ISSUE TITLE
Syntax highlighting does not work for some types

### ISSUE THREAD

**Issue by MrMho** [haberdashPI/vscode-neurobehave-presentation#1]
Hi,
first off, thanks for this extension. I very much prefer VS Code over Presentation's own editor. 

However, I noticed that some types which are highlighted by the Presentation editor are not highlighted by the extension. These include, for example:
- bool
- input_file
- wavefile 

I don't know whether this is expected behavior, but it would be nice to have syntax highlighting for all built-in types.

**Comment by haberdashPI** [comment]
Hi @MrMho, I'm glad to hear someone else is benefitting from the extension. 

I based my implementation off the documentation under [this link](https://www.neurobs.com/presentation/docs/index_html). I seemed to have missed bool, however. Where is `input_file` and `wavefile` documented? (I've found the documentation to be somewhat poorly organized). If you can point me to the specifications, I can include anything else I've missed. 

I've just made the changes to add the three keywords you've listed, and I'll push them shortly, after some tests.

More broadly speaking, I did not try to make this a perfect replica of the highlighting in the default editor: my goal was to create something usable without making it too complicated or painful to implement. If you have some specific requests for how the highlighting should work, I'm happy to add those, so long as they aren't too complicated to implement.

**Comment by haberdashPI** [comment]
Ah hah. I see, the documentation for those extra types are [here](https://www.neurobs.com/presentation/docs/index_html). I don't know if it makes sense to highlight all of those values. To do it well I would have to define a syntax format separately for the PCL header and for programmatic part of the document (where those types don't apply). Getting one part of the file to parse differently from another is actually a little hard to get right. I tried it, but it was too complicated for my purposes here, and I'm not sure it's really the intent of the basic TextMate grammar to do this sort of thing. 

I'll fix the problem with `bool` but I think fixing it to work with all of the general PCL types without mis-highlighting anything outside the PCL header might be an issue (unless you mean you would also want things like `wavefile` highlighting outside of the PCL header).

**Comment by haberdashPI** [comment]
One workaround could be highlighting anything just before `{`...

**Comment by haberdashPI** [comment]
Should be updated now. I've published v0.0.3 of the package to the marketplace.
